In [6]:
import numpy as np;

In [2]:
a=np.array([2,4,6,8,10])

In [3]:
print(a)

[ 2  4  6  8 10]


In [4]:
b=np.array([[1,3,5,],[7,9,11]])

In [5]:
print(b)

[[ 1  3  5]
 [ 7  9 11]]


In [6]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

In [7]:
print (c)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [10]:
arr=np.zeros((3,4))
print (arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [32]:
arr=np.ones((2,2))
print(arr)
arr=np.eye(3)
print(arr)

[[1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
import numpy as np
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
arr=np.linspace(1,20,6)
print(arr)

[ 1.   4.8  8.6 12.4 16.2 20. ]


In [39]:
a=np.array([2,4,6,8,10])
A=np.array([[1,3,5],[7,9,11]])
B=np.array([[[1,3,5],[7,9,11]],[[2,4,6],[8,10,12]],[[14,16,18],[20,22,24]]])
print(a[2])
print(A[0,2])
print(A[0,::2],A[1,::2])
print(B[2,1,::2])

6
5
[1 5] [ 7 11]
[20 24]


In [22]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

(2, 3)
6
2
int32


In [47]:
arr=np.arange(1,101)
newarr=arr.reshape(10,10)
print(newarr)
newarr=arr.reshape(2,10,5)
print(newarr)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
[[[  1   2   3   4   5]
  [  6   7   8   9  10]
  [ 11  12  13  14  15]
  [ 16  17  18  19  20]
  [ 21  22  23  24  25]
  [ 26  27  28  29  30]
  [ 31  32  33  34  35]
  [ 36  37  38  39  40]
  [ 41  42  43  44  45]
  [ 46  47  48  49  50]]

 [[ 51  52  53  54  55]
  [ 56  57  58  59  60]
  [ 61  62  63  64  65]
  [ 66  67  68  69  70]
  [ 71  72  73  74  75]
  [ 76  77  78  79  80]
  [ 81  82  83  84  85]
  [ 86  87  88  89  90]
  [ 91  92  93  94  95]
  [ 96  97  98  99 100]]]


In [46]:
arr=np.array([[[1,3,5],[7,9,11]],[[2,4,6],[8,10,12]],[[14,16,18],[20,22,24]]])
print(arr.flatten())

[ 1  3  5  7  9 11  2  4  6  8 10 12 14 16 18 20 22 24]


In [48]:
a=(1,2,3,4,5)
b=(6,7,8,9,10)
print(a+b)

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)


In [5]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a+10)
print(a*2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[11 12 13]
[2 4 6]


In [10]:
arr=np.array([10,20,30,40,50])
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))

150
30.0
50
10
14.142135623730951


In [9]:
a1=np.array([1,2,3,4,5,6,7,8,9,10])
print(a1.shape)
print(a1.dtype)
print(a1.size)

(10,)
int32
10


In [20]:
a3=np.array([1,2,3,4,5,6,7,18,9,10,11,12,13,14,15,16,17,8,19,20])
print(a3[0:10])
print(a3[14:])
print(list(range(0,20,2)))

[ 1  2  3  4  5  6  7 18  9 10]
[15 16 17  8 19 20]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [25]:
a4=np.array(range(1,13))
print(a4)
print(a4.reshape(3,4))
print(a4.reshape(2,6))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [27]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
